package control;

public enum Commands {

	C_SERVER, C_CLIENT, C_EXIT, C_ADD_BALL, C_SEND_MESSAGE, C_RUN_SERVER, C_CANCEL_SERVER, C_RUN_CLIENT,
	C_CANCEL_CLIENT,

	C_START, C_STOP_FIGURES, C_NEW_FIGURE, C_ADD_FIGURE, C_CONFIGURATION, C_CHOSE_COLOR, C_CLOSE_WINDOW;
}
